### ISSUE TITLE
FPort parameter missing on the rx msg.. (Need Help!!!)

### ISSUE THREAD

**Issue by sathishkumarparthiban** [ARMmbed/mbed-os-example-lorawan-fuota#10]
Hi All,

I have trying this with OTAA . 
i get the Clocksync on the topic "join"
Something like "application/1/device/badcfe0000000051/join"
So i edited the loraserver.js to also listen for this topic.
 ```
// only interested in rx for now...
    if (!((/\/rx$/.test(topic))||(/\/join$/.test(topic)))) return;
```

After this i can see the msg flow , but i dont get the fPort parameters in the msg.

```
msg {"applicationID":"1","applicationName":"STM_BOARD","deviceName":"STM_BOARD_DEV","devEUI":"badcfe0000000051","devAddr":"01eaeffd","rxInfo":[{"gatewayID":"333833304bffffffff","uplinkID":"6ab0042a-9a51-4a9a-8001-3ff8e72cf815","name":"MY_CHN_GW_001","rssi":-103,"loRaSNR":8,"location":{"latitude":0,"longitude":0,"altitude":0}}],"txInfo":{"frequency":865402500,"dr":0}}
topic application/1/device/badcfe0000000051/join
Rx application/1/device/badcfe0000000051/join {
  applicationID: '1',
  applicationName: 'STM_BOARD',
  deviceName: 'STM_BOARD_DEV',
  devEUI: 'badcfe0000000051',
  devAddr: '01eaeffd',
  rxInfo: [
    {
      gatewayID: '333833304bffffffff',
      uplinkID: '6ab0042a-9a51-4a9a-8001-3ff8e72cf815',
      name: 'MY_CHN_GW_001',
      rssi: -103,
      loRaSNR: 8,
      location: [Object]
    }
  ],
  txInfo: { frequency: 865402500, dr: 0 }
}
device found
port is
undefined

msg {"applicationID":"1","applicationName":"STM_BOARD","deviceName":"STM_BOARD_DEV","devEUI":"badcfe0000000051","rxInfo":[{"gatewayID":"333833304bffffffff","uplinkID":"6ad49160-5a09-48d7-8c84-a56674db193f","name":"MY_CHN_GW_001","rssi":-113,"loRaSNR":5.8,"location":{"latitude":0,"longitude":0,"altitude":0}}],"txInfo":{"frequency":865402500,"dr":0},"adr":true,"fCnt":28,"fPort":1,"data":"FQ=="}
topic application/1/device/badcfe0000000051/rx
Rx application/1/device/badcfe0000000051/rx {
  applicationID: '1',
  applicationName: 'STM_BOARD',
  deviceName: 'STM_BOARD_DEV',
  devEUI: 'badcfe0000000051',
  rxInfo: [
    {
      gatewayID: '333833304bffffffff',
      uplinkID: '6ad49160-5a09-48d7-8c84-a56674db193f',
      name: 'MY_CHN_GW_001',
      rssi: -113,
      loRaSNR: 5.8,
      location: [Object]
    }
  ],
  txInfo: { frequency: 865402500, dr: 0 },
  adr: true,
  fCnt: 28,
  fPort: 1,
  data: 'FQ=='
}
device found
port is
1
```

Can anyone say why is the port parameters not there in the message.. is there something that i miss here

**Comment by janjongboom** [comment]
@sathishkumarparthiban I'm not sure about your setup, but if you receive a clock sync in the join message (which does not seem to be on-spec) the port number is 0; and thus cannot be used to send a clock sync message back (because 0 is reserved).

**Comment by sathishkumarparthiban** [comment]
I'm using this application for embedded device.
https://github.com/Lora-net/LoRaMac-node/tree/develop/src/apps/LoRaMac/fuota-test-01/B-L072Z-LRWAN1 

My setup is 
Project : fuota-test-01
Board : B-L072Z-LRWAN1
Gateway : n-fuse 868Mhz (IN865-867 region).
Server: loraserver

I'm have been using this application as such without editing edited any code (expect for joining as OTAA instead of ABP).. 
so i would assume this application has been tested by many people already and would have it working..

**Comment by janjongboom** [comment]
@sathishkumarparthiban That application is completely unrelated to this repository. I'd recommand you open a bug there.
