### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by Devilal-Prajapat** [ARMmbed/mbed-os-example-lorawan-fuota#6]
Hello
Can we compile this project using ABP(Activation By personal)

**Comment by janjongboom** [comment]
Yes, replace the OTAA connect with: https://github.com/janjongboom/mbed-simulator/blob/master/demos/lorawan-abp/main.cpp#L90

**Comment by Devilal-Prajapat** [comment]
Hello
I am success in connecting 
but there is a query regarding update client APP_KEY if i define it as ABP there is no APP_key for my project. what should i replace this.
static LoRaWANUpdateClient uc(&bd, **APP_KEY,** lora_uc_send);

**Comment by janjongboom** [comment]
This is the GenAppKey used for multicast. This is a separate key from your OTAA key (although in this example I used the same key). See https://lora-alliance.org/sites/default/files/2018-09/remote_multicast_setup_v1.0.0.pdf

**Comment by Devilal-Prajapat** [comment]
Thanks.

**Comment by Devilal-Prajapat** [comment]
Can we use internal flash of board as it contain 1MB flash. As of now Binary size for project is not exceeding 300KB.  
what changes should I have to made for this.

**Comment by janjongboom** [comment]
Yes, use the [FlashIAPBlockDevice](https://os.mbed.com/docs/mbed-os/v5.13/apis/flashiapblockdevice.html) driver to mount part of your file system on internal flash. Details are here: https://github.com/ARMmbed/mbed-os-example-lorawan-fuota/blob/master/docs/porting-guide.md#storage-layer, but as I no longer work for Arm I personally won't be able to help with the actual porting.

**Comment by Devilal-Prajapat** [comment]
Thanks.
